<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoucherTypeMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'voucher_type_id' => -99,
                'voucher_type_id_string' => '11',
                'voucher_name' => 'OPENING BALANCE',
                'voucher_name_alias' => 'OPENING BALANCE',
                'voucher_prefix' => 'OB',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 1,
                'voucher_type_id_string' => '01',
                'voucher_name' => 'PAYMENT VOUCHER',
                'voucher_name_alias' => 'PAYMENT VOUCHER',
                'voucher_prefix' => 'PV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 2,
                'voucher_type_id_string' => '02',
                'voucher_name' => 'RECEIPT VOUCHER',
                'voucher_name_alias' => 'RECEIPT VOUCHER',
                'voucher_prefix' => 'RV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 3,
                'voucher_type_id_string' => '03',
                'voucher_name' => 'SALES VOUCHER',
                'voucher_name_alias' => 'SALES VOUCHER',
                'voucher_prefix' => 'SV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 4,
                'voucher_type_id_string' => '04',
                'voucher_name' => 'PURCHASE VOUCHER',
                'voucher_name_alias' => 'PURCHASE VOUCHER',
                'voucher_prefix' => 'GV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 5,
                'voucher_type_id_string' => '05',
                'voucher_name' => 'JOURNAL VOUCHER',
                'voucher_name_alias' => 'JOURNAL VOUCHER',
                'voucher_prefix' => 'JV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 6,
                'voucher_type_id_string' => '06',
                'voucher_name' => 'CONTRA VOUCHER',
                'voucher_name_alias' => 'CONTRA VOUCHER',
                'voucher_prefix' => 'CO',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 7,
                'voucher_type_id_string' => '07',
                'voucher_name' => 'CREDIT NOTE',
                'voucher_name_alias' => 'CREDIT NOTE',
                'voucher_prefix' => 'CN',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 8,
                'voucher_type_id_string' => '08',
                'voucher_name' => 'DEBIT NOTE',
                'voucher_name_alias' => 'DEBIT NOTE',
                'voucher_prefix' => 'DN',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 9,
                'voucher_type_id_string' => '09',
                'voucher_name' => 'INCOME VOUCHER',
                'voucher_name_alias' => 'INCOME VOUCHER',
                'voucher_prefix' => 'IV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 10,
                'voucher_type_id_string' => '10',
                'voucher_name' => 'EXPENSE VOUCHER',
                'voucher_name_alias' => 'EXPENSE VOUCHER',
                'voucher_prefix' => 'EV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 101,
                'voucher_type_id_string' => '04-01',
                'voucher_name' => 'PURCHASE TRADING',
                'voucher_name_alias' => 'PURCHASE VOUCHER',
                'voucher_prefix' => 'GV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 102,
                'voucher_type_id_string' => '03-01',
                'voucher_name' => 'SALES TRADING',
                'voucher_name_alias' => 'SALES VOUCHER',
                'voucher_prefix' => 'SV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 103,
                'voucher_type_id_string' => '01-01',
                'voucher_name' => 'PAYMENT TRADING',
                'voucher_name_alias' => 'PAYMENT VOUCHER',
                'voucher_prefix' => 'PV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 104,
                'voucher_type_id_string' => '02-01',
                'voucher_name' => 'RECEIPT TRADING',
                'voucher_name_alias' => 'RECEIPT VOUCHER',
                'voucher_prefix' => 'RV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 105,
                'voucher_type_id_string' => '03-02',
                'voucher_name' => 'SALES COUNTER',
                'voucher_name_alias' => 'SALES VOUCHER',
                'voucher_prefix' => 'SC',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 106,
                'voucher_type_id_string' => '01-02',
                'voucher_name' => 'PAYMENT VOUCHER',
                'voucher_name_alias' => 'PAYMENT VOUCHER',
                'voucher_prefix' => 'PV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 107,
                'voucher_type_id_string' => '02-01',
                'voucher_name' => 'RECEIPT VOUCHER',
                'voucher_name_alias' => 'RECEIPT VOUCHER',
                'voucher_prefix' => 'RV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 108,
                'voucher_type_id_string' => '09-01',
                'voucher_name' => 'INCOME VOUCHER',
                'voucher_name_alias' => 'INCOME VOUCHER',
                'voucher_prefix' => 'IV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 109,
                'voucher_type_id_string' => '10-01',
                'voucher_name' => 'EXPENSE VOUCHER',
                'voucher_name_alias' => 'EXPENSE VOUCHER',
                'voucher_prefix' => 'EV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 110,
                'voucher_type_id_string' => '06-01',
                'voucher_name' => 'CONTRA VOUCHER',
                'voucher_name_alias' => 'INCOME VOUCHER',
                'voucher_prefix' => 'CO',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 111,
                'voucher_type_id_string' => '04-02',
                'voucher_name' => 'PURCHASE VOUCHER',
                'voucher_name_alias' => 'PURCHASE VOUCHER',
                'voucher_prefix' => 'GV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'voucher_type_id' => 112,
                'voucher_type_id_string' => '05-01',
                'voucher_name' => 'JOURNAL VOUCHER',
                'voucher_name_alias' => 'JOURNAL VOUCHER',
                'voucher_prefix' => 'JV',
                'no_method' => 'AUTO',
                'voucher_no_rest_date' => '2011-12-12 00:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('voucher_type_master')->insert($data);
    }
}
